"""Build the chunk-5 readout for Roger: every chunk-5 entry that is ready or
generated, with its description, the antonym check's answer, the reviewer's
issues and the writer's notes, grouped by sub-chunk, plus the decisions that
wait on him.  Regenerate after every round; it reads the queue and the review
files only.

    uv run python roger/chunk5_2026-10-08/make_readout.py
"""
import json
from pathlib import Path

D = Path("roger/chunk5_2026-10-08")
OUT = D / "readout_chunk5.md"
QUEUE = Path("data/seed_queue.json")
CORPUS = Path("data/traits/instructions")
GROUPS = [
    ("5A: unpaired plain traits", "entries_5a_unpaired.json", "review_5a.json"),
    ("5B: membership sets", "entries_5b_sets.json", "review_5b_sets.json"),
    ("5B: nationality and ethnicity maps", "entries_5b_maps.json", "review_5b_maps.json"),
    ("5C: the two triangles", "entries_5c_triangles.json", "review_5c_triangles.json"),
]
HELD = {"ageist", "sexist", "xenophobic", "self_harming", "suicidal", "kinky"}


def link(stem: str) -> str:
    p = CORPUS / f"{stem}.json"
    rel = f"../../data/traits/instructions/{stem}.json"
    return f"[{stem}]({rel})" if p.exists() else f"[{stem}]({rel}) (not seeded yet)"


def main() -> None:
    q = json.load(open(QUEUE, encoding="utf-8"))
    by = {e["stem"]: e for e in q["entries"]}
    # an entry renamed since the writers' entries files were split is found by its old stem too
    for e in q["entries"]:
        rf = e.get("renamed_from")                      # a dict on new entries, a bare stem on older ones
        old = rf.get("stem") if isinstance(rf, dict) else rf
        if old and old not in by:
            by[old] = e
    out = ["# Chunk 5 readout (generated " + __import__("datetime").date.today().isoformat() + ")", "",
           "Written for Roger.  Every entry of chunk 5 that has a description, grouped as the writers had",
           "them: the description as it now stands in the queue (the reviewer's edit where one was made),",
           "the antonym check's answer (`returned (category)`; for an unpaired trait the answer is a",
           "candidate label for later, recorded in the check history), the reviewer's issues and the",
           "writer's notes, condensed.  Files are linked where they exist.  The decisions that wait on you",
           "are in the chat; this file is the reading list.  Regenerated by",
           "[make_readout.py](./make_readout.py) after each round.", ""]
    for title, entries_f, review_f in GROUPS:
        if not (D / entries_f).exists():
            continue
        entries = json.load(open(D / entries_f, encoding="utf-8"))
        review = {}
        if (D / review_f).exists():
            review = {r["stem"]: r for r in json.load(open(D / review_f, encoding="utf-8"))["entries"]}
        out += [f"## {title}", ""]
        for ent in entries:
            e = by[ent["stem"]]
            if not e.get("description"):
                continue
            cr = e.get("check_result") or {}
            status = e.get("status")
            tag = " **(held for the sensitive batch)**" if e["stem"] in HELD else ""
            words = len(e["description"].split())
            out.append(f"### {link(e['stem'])}  `{e['label']}`  ({words} w, {status}){tag}")
            out.append("")
            out.append(f"> {e['description']}")
            out.append("")
            if cr:
                out.append(f"- check: `{cr.get('returned')}` ({cr.get('category')}, score {cr.get('score')})")
            r = review.get(e["stem"])
            if r:
                if r.get("verdict") == "edit" and r.get("suggested_edit"):
                    out.append(f"- reviewer: EDIT applied; was: {e.get('description_draft')}")
                for iss in r.get("issues") or []:
                    out.append(f"- reviewer: {iss}")
                if r.get("trim_to_32"):
                    out.append(f"- trim to 32: {r['trim_to_32']}")
            if e.get("notes") and e.get("notes") != e.get("description_notes"):
                note = e["notes"] if isinstance(e["notes"], str) else json.dumps(e["notes"])
                out.append(f"- writer: {note[:600]}")
            if e.get("nearest_existing"):
                out.append(f"- nearest existing: {str(e['nearest_existing'])[:400]}")
            if e.get("hand_edits") or (CORPUS / f"{e['stem']}.json").exists() and json.load(open(CORPUS / f"{e['stem']}.json")).get("hand_edits"):
                out.append("- hand edit: p4 opening rewritten (doubled form after two generations)")
            out.append("")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(out)} lines)")


if __name__ == "__main__":
    main()
